export const devices = [
  { name: 'iPhone 12 Pro', width: 390, height: 844, category: 'mobile' },
  { name: 'iPhone SE', width: 375, height: 667, category: 'mobile' },
  { name: 'Pixel 5', width: 393, height: 851, category: 'mobile' },
  { name: 'Samsung Galaxy S20', width: 360, height: 800, category: 'mobile' },
  { name: 'iPhone 13 Mini', width: 375, height: 812, category: 'mobile' },
  { name: 'Google Pixel 4', width: 353, height: 745, category: 'mobile' },
  { name: 'OnePlus 9', width: 412, height: 915, category: 'mobile' },
  { name: 'iPad Air', width: 820, height: 1180, category: 'tablet' },
  { name: 'iPad Mini', width: 768, height: 1024, category: 'tablet' },
  { name: 'Surface Pro 7', width: 912, height: 1368, category: 'tablet' },
  { name: 'Galaxy Tab S7', width: 800, height: 1280, category: 'tablet' },
  { name: 'iPad Pro 11"', width: 834, height: 1194, category: 'tablet' },
  { name: 'Nexus 9', width: 1024, height: 768, category: 'tablet' },
  { name: 'Kindle Fire HDX', width: 800, height: 1280, category: 'tablet' },
  { name: 'Nest Hub Max', width: 1280, height: 800, category: 'tablet' },
];
